# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Pagination
#
# Including the gem for pagination

plugins:
  - jekyll-paginate
  - jekyll-gist

# Localization
#
# Strings for Localization

services:
  de: "leistungen"
  en: "services"

about:
  de: "über mich"
  en: "about me"

contact:
  de: "kontakt"
  en: "contact"

badges:
  de: "bapperl"
  en: "badges"

legal:
  de: "impressum"
  en: "legal notice"

privacy:
  de: "datenschutzerklärung"
  en: "privacy policy"

feed:
  de: "Web-Feed"
  en: "Web feed"

back:
  de: "&laquo; Zurück zur Hauptseite"
  en: "&laquo; Back to front page"

# Setup
title:               "ChristophRoeper(roeper.biz) {}"
tagline:             vCard/Blog
paginate:            3
url:                 https://roeper.biz/
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About me / Contact
author:
  name:              Christoph Roeper
  full_name:         Christoph W. Roeper
  company:           Christoph Roeper - roeper.biz
  vat_id:            "DE174675273"
  street:            "Augustastr. 5"
  zip:               52070
  city:              "Aachen"
  country:
    de:              "Deutschland"
    en:              "Germany"
  position:
    de:              "50° 46,377' N 006° 05,810' E"
    en:              "50° 46.377' N 006° 05.810' E"
  phone:             "+49 241 9904183"
  email:             info@roeper.biz
  web:               www.roeper.biz
  twitter:           "skipperTux"
  stackOverflow:     "skipperTux"
  gitHub:            "skipperTux"

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/poole/poole

# Polyglot
#
# We specify the used languages so we can use Polyglot to localize
languages: ["de", "en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]

exclude:
  - badge_thumbs.sh
  - build.sh
  - clean.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - serve.sh
  - vendor/
