# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Pagination
#
# Including the gem for pagination

gems:
  - jekyll-paginate
  - jekyll-gist

# Localization
#
# Strings for Localization

services:
  de: "leistungen"
  en: "services"

about:
  de: "체ber mich"
  en: "about me"

contact:
  de: "kontakt"
  en: "contact"

legal:
  de: "impressum"
  en: "legal notice"
  
feed:
  de: "Web-Feed"
  en: "Web feed"

back:
  de: "&laquo; Zur체ck zur Hauptseite"
  en: "&laquo; Back to front page"

# Setup
title:               "ChristophRoeper(roeper.biz) {}"
tagline:             vCard/Blog
url:                 http://roeper.biz/
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christoph W. Roeper
  company:           Christoph Roeper - roeper.biz           
  phone:             "+49 241 9904183"
  email:             info@roeper.biz
  web:               www.roeper.biz
  twitter:           https://twitter.com/skipperTux
  twitterName:       "skipperTux"
  github:            https://github.com/skipperTux
  githubName:        "skipperTux"
  stackOverflow:     https://stackoverflow.com/users/498352/skippertux?tab=profile
  stackOverflowName: "skipperTux"
  linkedin:          https://de.linkedin.com/in/roeperdotbiz
  vat-id:            "DE174675273"
  street:            "Augustastr. 5"
  zip:               52070
  city:              "Aachen"
  country:
    de:              "Deutschland"
    en:              "Germany"
  position:          https://www.openstreetmap.org/?mlat=50.77295&mlon=6.09684
  positionName:      "50째 46.377' N  006째 05.810' E"    

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Polyglot
#
# We specify the used languages so we can use Polyglot to localize
languages: ["de", "en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]

exclude: [README.md, Gemfile, Gemfile.lock]
